direction : right

	1 : 루트 페이지 접속
	2 : 상품 리스트 조회
	3 : 루트 페이지 에서
	4 : 로그인 페이지에서
	5 : 상품 디테일 페이지에서
	6 : 장바구니에서
	7 : 로그인
	8 : 회원가입 페이지
	9 : 장바구니에 추가
	10 : 장바구니에서 제거
	11 : 장바구니 수량 변경
	12 : 결제
	13 : 관리자 페이지에서
	14 : 판매 검토
	15 : 머신러닝 예측 결과 검토

	1 -> 2
	2 -> 3
	3 -> 4
	3 -> 5
	3 -> 6
	4 -> 7
	4 -> 8
	5 -> 9
	6 -> 10
	6 -> 11
	6 -> 12
	3 -> 13
	13 -> 14
	13 -> 15
