java: {  
    spring: {  
      thymeleaf <-> _._.Web  
      jpa <-> _._.DB  
    }  
  }  
  Web: {  
    Bootstrap: {  
      CSS  
      JS  
    }  
  }  
  DB: {  
    Mysql  
  }  
  Python: {  
    near: bottom-center
    
    FastAPI -> _.Web  
    ML model <-> _.DB  
  }